//这里暂定为只有2级菜单
export default [
    {
        name:'组件1（路由）',
        path:'/page/admin/component1',
        hasChildren:false
    },
    {
        name:'父菜单1',
        hasChildren:true,
        children:[
            {
                name:'组件2',
                path:'/page/admin/component2',
                hasChildren:false
            },
            {
                name:'组件3',
                path:'/page/admin/component3',
                hasChildren:false
            }
        ],
        open:true
    },
    {
        name:'路由3',
        path:'/page/admin/component3',
        hasChildren:false,
    },
    {
        name:'父菜单2',
        hasChildren:true,
        children:[
            {
                name:'组件2-2',
                path:'/page/admin/component2',
                hasChildren:false
            },
            {
                name:'组件2-3',
                path:'/page/admin/component3',
                hasChildren:false
            }
        ],
        open:false
    }
]

export const height = 41;